### ISSUE TITLE
FrancoisDeBellescize Fork crashing

### ISSUE THREAD

**Issue by Crox77** [wylanswets/homebridge-sure-petcare-platform#29]
@FrancoisDeBellescize I have been using your fork since June 2023 but keep getting this error message today causing a Homebridge Sigterm

TypeError: Cannot read properties of undefined (reading 'where')
    at SurePetcareOccupancySensor.pollStatus (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/accessories/SurePetcareOccupancySensor.js:29:42)
    at /usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/index.js:75:15
    at /usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:103:17
    at Request._callback (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:131:17)
    at Request.self.callback (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)

I have now added it as a child bridge so all my other home bridge items work

Can you please fix this great plugin again as you did in June last year?

Many Thanks

**Comment by Crox77** [comment]
Any chance of an update to fix the issue of the plug-in keep crashing please?

**Comment by LeviJSmith** [comment]
I'm seeing this error as well.  Any updates on a fix?

**Comment by Crox77** [comment]
Hi so 2 months since the plugin stopped working! Any chance of an update please?

**Comment by lieberjott** [comment]
Experiencing the same issue since yesterday. Came out of the blue, I haven't changed anything.

**Comment by Crox77** [comment]
> Experiencing the same issue since yesterday. Came out of the blue, I haven't changed anything.

Mine has been like it for nearly a year now. I’m guessing there won’t be any update or fix sadly

**Comment by lieberjott** [comment]
I was able to solve this issue for me!
The crash log gave a hint, that the occupancy sensor seems to cause the problem, so I simply disabled this feature in the JSON settings:

`{
    "platform": "SurePetcare",
    "name": "SurePetcare",
    "email": "xxxxxxx",
    "password": "xxxxxxxxx",
    "poll_interval": 120,
    "pet_occupancy": false,
    "lock_mode": 2
}`

I guess this was caused by some change at Sure Petcare cloud, because I noticed, that the native App was also behaving a bit different in terms of pet is at home/out of home.

Another solution approach is to run the petcare plugin as a sub-bridge, see https://github.com/wylanswets/homebridge-sure-petcare-platform/issues/22#issuecomment-972167602

**Comment by Crox77** [comment]
> I was able to solve this issue for me! The crash log gave a hint, that the occupancy sensor seems to cause the problem, so I simply disabled this feature in the JSON settings:
> 
> `{ "platform": "SurePetcare", "name": "SurePetcare", "email": "xxxxxxx", "password": "xxxxxxxxx", "poll_interval": 120, "pet_occupancy": false, "lock_mode": 2 }`
> 
> I guess this was caused by some change at Sure Petcare cloud, because I noticed, that the native App was also behaving a bit different in terms of pet is at home/out of home.
> 
> Another solution approach is to run the petcare plugin as a sub-bridge, see [#22 (comment)](https://github.com/wylanswets/homebridge-sure-petcare-platform/issues/22#issuecomment-972167602)

Hi Ive now set Occupancy to false but get tis error message.

/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:131
                callback(body);
                ^
TypeError: acc.pollStatus is not a function
    at /usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/index.js:75:15
    at /usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:103:17
    at Request._callback (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:131:17)
    at Request.self.callback (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)

I also have always run my plugin as a child bridge to stop home bridge crashing

**Comment by FrancoisDeBellescize** [comment]
Hi guys,

Thanks for the issue, I'll try to give a look this week, sorry for the delay :/

**Comment by Crox77** [comment]
> Hi guys,
> 
> Thanks for the issue, I'll try to give a try this week, sorry for the delay :/

Brilliant Francois. Thank You

**Comment by FrancoisDeBellescize** [comment]
Hi huys !

You can now install the version `0.1.10` of my fork.

The problem is : The SurePetCare team is not sending anymore the pet position, i think this is a bug on their side.
So i made a fix and the plugin won't crash anymore because of that but the occupation sensor should not work anymore until they make a fix ...

**Comment by Crox77** [comment]
> Hi huys !
> 
> You can now install the version `0.1.10` of my fork.
> 
> The problem is : The SurePetCare team is not sending anymore the pet position, i think this is a bug on their side. So i made a fix and the plugin won't crash anymore because of that but the occupation sensor should not work anymore until they make a fix ...

Thanks Francois

I am still getting the plugin crashing though:

/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:131
                callback(body);
                ^
TypeError: acc.pollStatus is not a function
    at /usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/index.js:75:15
    at /usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:103:17
    at Request._callback (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/@francoisdebellescize/sure_petcare/dist/lib.js:131:17)
    at Request.self.callback (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@francoisdebellescize/homebridge-sure-petcare-platform/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)

Here is my config:

**Comment by Crox77** [comment]
Brilliant thank you so much Francois. After 11 months of this not working it’s great to have it back

**Comment by Crox77** [comment]
Hi Francois

Is the plugging going to work with Homebridge 2.0? 

Many Thanks
Paul

**Comment by FrancoisDeBellescize** [comment]
Hi !

Yes, I need some time to make it work, I'll add it to my to do list 😅

**Comment by Crox77** [comment]
> Hi !
> 
> Yes, I need some time to make it work, I'll add it to my to do list 😅


Great stuff Francois, you’re a star. I’m holding off updating to HB2.0 as waiting on a couple other plugins to update. 
Thank You as always

**Comment by FrancoisDeBellescize** [comment]
I have updated the package to handle the Homebridge 2.0

Seems to work with the legacy 1.X and I'm now trying with the 2.X version
